version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: mcp-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - mcp-network # Ensure this network is defined in your main docker-compose.yml or here
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: mcp-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      # Example for provisioning datasources and dashboards
      # - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning # For datasources.yml, dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards # For dashboard JSON files
    ports:
      - "127.0.0.1:3003:3000" # Changed from 3000:3000 to 3003:3000 to avoid common conflicts
    networks:
      - mcp-network
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus-data:
    name: mcp-prometheus-data
  grafana-data:
    name: mcp-grafana-data

networks:
  mcp-network:
    # If this network is defined in another docker-compose file and is intended to be shared,
    # mark it as external. Otherwise, define it here.
    # external: true 
    name: mcp-network # Explicitly naming it, can be omitted if default name is fine
    driver: bridge # Default driver
