version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: mcp-mitre-attack
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./db:/app/db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_PATH=/app/db/mcp.sqlite3
      - LOG_LEVEL=debug
    restart: unless-stopped
    command: npm run dev

volumes:
  node_modules:
